/*
 * SPDX-FileCopyrightText: 2026 陈轩 <2811158416@qq.com>
 * SPDX-License-Identifier: Apache-2.0
 *
 * First published in this repository: 2026-04-06
 * Use of this file is governed by the LICENSE file in the repository root.
 */

#pragma once

#define ARBATOS_TARGET_NAME "SENTINEL-M"
#define ARBATOS_BOARD_NAME "DmMc02H7"
#define ROBOT_PROFILE_KIND ROBOT_PROFILE_KIND_SENTRY
#define ROBOT_BOARD_KIND ROBOT_BOARD_KIND_STM32H7
#define ROBOT_BOARD_CPU_HZ 500000000u
#define ROBOT_BOARD_CAN_BUS_COUNT 2u
#define ROBOT_BOARD_HAS_FPU 1u

#define MOTOR_ARM_JOINT_COUNT 6u
#define CHASSIS_USE_IMU_YAW_FEEDBACK 1u
#define CHASSIS_GIMBAL_YAW_RELATIVE_TURN 1u
#define GIMBAL_USE_ENCODER_FEEDBACK 0u
#define GIMBAL_DUAL_YAW_IMU_TURN 0u
#define GIMBAL_PITCH_MIDDLE_ECD 3600u
#define GIMBAL_PITCH_HOLD_CURRENT 6000.0f
#define CHASSIS_STOP_ON_GIMBAL_STATE 0u

#define WATCH_ENABLE_LOCOMOTION_CLASSIC 1
#define WATCH_ENABLE_LOCOMOTION_WHEELLEG_SERVO 0
#define WATCH_ENABLE_LOCOMOTION_WHEELLEG_MIT 0
#define WATCH_ENABLE_GIMBAL_SINGLE 1
#define WATCH_ENABLE_GIMBAL_DUAL 1
#define WATCH_ENABLE_SHOOT_RM 1
#define WATCH_ENABLE_ARM_J0_UNITREE 0
#define WATCH_ENABLE_RUNTIME_COPY 0
#define WATCH_ENABLE_COMM_COPY 0
#define WATCH_ENABLE_DIAG_COPY 0

#define ROBOT_TASK_BUILD_STARTUP_SERVICE 0
#define ROBOT_TASK_BUILD_CALIBRATION 0
#define ROBOT_TASK_BUILD_RC_SBUS 1
#define ROBOT_TASK_BUILD_HEALTH_MONITOR 1
#define ROBOT_TASK_BUILD_SDLOG 1
#define ROBOT_TASK_BUILD_CAN_COMMAND_TX 1
#define ROBOT_TASK_BUILD_CAN_FEEDBACK_RX 1
#define ROBOT_TASK_BUILD_CLASSIC_CHASSIS 1
#define ROBOT_TASK_BUILD_WHEELLEG_SERVO 0
#define ROBOT_TASK_BUILD_WHEELLEG_MIT 0
#define ROBOT_TASK_BUILD_SINGLE_GIMBAL 0
#define ROBOT_TASK_BUILD_DUAL_YAW_GIMBAL 1
#define ROBOT_TASK_BUILD_ARM 0
#define ROBOT_TASK_BUILD_IMU 1
#define ROBOT_TASK_BUILD_HOST_LINK 1
#define ROBOT_TASK_BUILD_ELRS_LINK 0
#define ROBOT_TASK_BUILD_REFEREE_RX 0
#define ROBOT_TASK_BUILD_BATTERY_MONITOR 0
#define ROBOT_TASK_BUILD_SERVO 0
#define ROBOT_TASK_BUILD_STATUS_LED 0
#define ROBOT_TASK_BUILD_SHOOT_RM 1

#include "RobotConfigTypes.h"
