/*
 * SPDX-FileCopyrightText: 2026 Xie Yuhan <2811158416@qq.com>
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ROBOT_FAULT_TYPES_H
#define ROBOT_FAULT_TYPES_H

typedef enum
{
    ROBOT_FAULT_REASON_NONE = 0u,
    ROBOT_FAULT_REASON_STACK_OVERFLOW = 1u,
    ROBOT_FAULT_REASON_MALLOC_FAILED = 2u,
    ROBOT_FAULT_REASON_ERROR_HANDLER = 3u,
    ROBOT_FAULT_REASON_HARDFAULT = 4u,
    ROBOT_FAULT_REASON_MEMMANAGE = 5u,
    ROBOT_FAULT_REASON_BUSFAULT = 6u,
    ROBOT_FAULT_REASON_USAGEFAULT = 7u,
    ROBOT_FAULT_REASON_NMI = 8u,
    ROBOT_FAULT_REASON_ASSERT = 9u,
    ROBOT_FAULT_REASON_SCHEDULER_RETURN = 10u,
    ROBOT_FAULT_REASON_DEFAULT_INTERRUPT = 11u,
} RobotFaultReason;

#endif
