#ifndef BSP_BMI088_CFG_H
#define BSP_BMI088_CFG_H

#include "bsp_board_ports.h"

#define BSP_BMI088_SPI_HANDLE         BSP_BOARD_BMI088_SPI_HANDLE
#define BSP_BMI088_ACCEL_CS_GPIO_Port BSP_BOARD_BMI088_ACCEL_CS_GPIO_Port
#define BSP_BMI088_ACCEL_CS_Pin       BSP_BOARD_BMI088_ACCEL_CS_Pin
#define BSP_BMI088_GYRO_CS_GPIO_Port  BSP_BOARD_BMI088_GYRO_CS_GPIO_Port
#define BSP_BMI088_GYRO_CS_Pin        BSP_BOARD_BMI088_GYRO_CS_Pin

#define BSP_BMI088_SKIP_SELF_TEST     1

#endif
