/*
 * SPDX-FileCopyrightText: 2026 陈轩 <2811158416@qq.com>
 * SPDX-License-Identifier: Apache-2.0
 *
 * First published in this repository: 2026-04-06
 * Use of this file is governed by the LICENSE file in the repository root.
 */

#pragma once

#define ARBATOS_TARGET_NAME "HERO-M"
#define ARBATOS_BOARD_NAME "DM_MC02_H7"
#define ROBOT_PROFILE_KIND ROBOT_PROFILE_KIND_HERO
#define ROBOT_BOARD_KIND ROBOT_BOARD_KIND_STM32H7
#define ROBOT_BOARD_CPU_HZ 500000000u
#define ROBOT_BOARD_CAN_BUS_COUNT 2u
#define ROBOT_BOARD_HAS_FPU 1u

#define MOTOR_ARM_JOINT_COUNT 6u

#define ROBOT_TASK_BUILD_STARTUP_SERVICE 0
#define ROBOT_TASK_BUILD_CALIBRATION 0
#define ROBOT_TASK_BUILD_RC_SBUS 1
#define ROBOT_TASK_BUILD_HEALTH_MONITOR 1
#define ROBOT_TASK_BUILD_SDLOG 1
#define ROBOT_TASK_BUILD_CAN_COMMAND_TX 1
#define ROBOT_TASK_BUILD_CAN_FEEDBACK_RX 1
#define ROBOT_TASK_BUILD_CLASSIC_CHASSIS 1
#define ROBOT_TASK_BUILD_WHEELLEG_SERVO 0
#define ROBOT_TASK_BUILD_WHEELLEG_MIT 0
#define ROBOT_TASK_BUILD_SINGLE_GIMBAL 1
#define ROBOT_TASK_BUILD_DUAL_YAW_GIMBAL 0
#define ROBOT_TASK_BUILD_ARM 0
#define ROBOT_TASK_BUILD_IMU 1
#define ROBOT_TASK_BUILD_HOST_LINK 0
#define ROBOT_TASK_BUILD_ELRS_LINK 0
#define ROBOT_TASK_BUILD_REFEREE_RX 1
#define ROBOT_TASK_BUILD_BATTERY_MONITOR 1
#define ROBOT_TASK_BUILD_SERVO 0
#define ROBOT_TASK_BUILD_STATUS_LED 0
#define ROBOT_TASK_BUILD_SHOOT_RM 1

#include "RobotConfigTypes.h"
