/*
 * SPDX-FileCopyrightText: 2026 陈轩 <2811158416@qq.com>
 * SPDX-License-Identifier: Apache-2.0
 *
 * First published in this repository: 2026-04-06
 * Use of this file is governed by the LICENSE file in the repository root.
 */

#pragma once

#define ARBATOS_TARGET_NAME "MINIWHEELEG-C"
#define ARBATOS_BOARD_NAME "DJI_C_F407"
#define ROBOT_PROFILE_KIND ROBOT_PROFILE_KIND_WHEELLEG
#define ROBOT_BOARD_KIND ROBOT_BOARD_KIND_STM32F407
#define ROBOT_BOARD_CPU_HZ 168000000u
#define ROBOT_BOARD_CAN_BUS_COUNT 2u
#define ROBOT_BOARD_HAS_FPU 1u

#define MOTOR_ARM_JOINT_COUNT 6u

#define WATCH_ENABLE_LOCOMOTION_CLASSIC 0
#define WATCH_ENABLE_LOCOMOTION_WHEELLEG_SERVO 0
#define WATCH_ENABLE_LOCOMOTION_WHEELLEG_MIT 1
#define WATCH_ENABLE_GIMBAL_SINGLE 0
#define WATCH_ENABLE_GIMBAL_DUAL 0
#define WATCH_ENABLE_SHOOT_RM 0
#define WATCH_ENABLE_ARM_J0_UNITREE 0

#define MINIWHEELEG_MIT_MOTOR_CAN_BUS 1u

/* C board is mounted with the wheel-leg body pitch on INS roll. */
#define WHEELLEG_IMU_BODY_ROLL_OFFSET INS_PITCH_ADDRESS_OFFSET
#define WHEELLEG_IMU_BODY_PITCH_OFFSET INS_ROLL_ADDRESS_OFFSET
#define WHEELLEG_IMU_BODY_GYRO_X_OFFSET INS_GYRO_Y_ADDRESS_OFFSET
#define WHEELLEG_IMU_BODY_GYRO_Y_OFFSET INS_GYRO_X_ADDRESS_OFFSET
#define WHEELLEG_IMU_ROLL_SIGN (-1.0f)
#define WHEELLEG_IMU_PITCH_SIGN (1.0f)
#define WHEELLEG_IMU_GYRO_X_SIGN (-1.0f)
#define WHEELLEG_IMU_GYRO_Y_SIGN (1.0f)
#define WHEELLEG_BENCH_TARGET_FOOT_X_M 0.0f

#include "robot_config_types.h"
