/*
 * SPDX-FileCopyrightText: 2026 Xie Yuhan <2811158416@qq.com>
 * SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
 */

#ifndef ROBOT_CONFIG_SCHEMA_H
#define ROBOT_CONFIG_SCHEMA_H

#include <stdint.h>

#include "actuator_cmd.h"

#ifndef ROBOT_TASK_MODULE_MAX
#define ROBOT_TASK_MODULE_MAX 16u
#endif

typedef enum
{
    ROBOT_TASK_MODULE_NONE = 0u,
    ROBOT_TASK_MODULE_RC_SBUS = 1u,
    ROBOT_TASK_MODULE_HEALTH_MONITOR = 2u,
    ROBOT_TASK_MODULE_SDLOG = 3u,
    ROBOT_TASK_MODULE_CAN_COMMAND_TX = 4u,
    ROBOT_TASK_MODULE_CAN_FEEDBACK_RX = 5u,
    ROBOT_TASK_MODULE_CLASSIC_CHASSIS = 6u,
    ROBOT_TASK_MODULE_WHEELLEG_SERVO = 7u,
    ROBOT_TASK_MODULE_WHEELLEG_MIT = 8u,
    ROBOT_TASK_MODULE_SINGLE_GIMBAL = 9u,
    ROBOT_TASK_MODULE_DUAL_YAW_GIMBAL = 10u,
    ROBOT_TASK_MODULE_ARM = 11u,
    ROBOT_TASK_MODULE_IMU = 12u,
    ROBOT_TASK_MODULE_HOST_LINK = 13u,
    ROBOT_TASK_MODULE_ELRS_LINK = 14u,
    ROBOT_TASK_MODULE_REFEREE_RX = 15u,
    ROBOT_TASK_MODULE_BATTERY_MONITOR = 16u,
    ROBOT_TASK_MODULE_SERVO = 17u,
    ROBOT_TASK_MODULE_CALIBRATION = 18u,
    ROBOT_TASK_MODULE_STATUS_LED = 19u,
    ROBOT_TASK_MODULE_STARTUP_SERVICE = 20u,
} robot_task_module_e;

typedef struct
{
    uint8_t task_module_count;
    uint8_t task_modules[ROBOT_TASK_MODULE_MAX];
} task_profile_t;

#ifndef MOTOR_ARM_JOINT_COUNT
#define MOTOR_ARM_JOINT_COUNT 0u
#endif

#ifndef ROBOT_DEVICE_CONFIG_MAX
#define ROBOT_DEVICE_CONFIG_MAX (12u + MOTOR_ARM_JOINT_COUNT)
#endif

#define ROBOT_DEVICE_TABLE_KIND_MOTOR 1u

#define ROBOT_DEVICE_CONFIG_REF_NONE 0u
#define ROBOT_DEVICE_CONFIG_REF_MOTOR_CHASSIS 1u
#define ROBOT_DEVICE_CONFIG_REF_MOTOR_YAW 2u
#define ROBOT_DEVICE_CONFIG_REF_MOTOR_YAW_UPPER 3u
#define ROBOT_DEVICE_CONFIG_REF_MOTOR_PITCH 4u
#define ROBOT_DEVICE_CONFIG_REF_MOTOR_TRIGGER 5u
#define ROBOT_DEVICE_CONFIG_REF_MOTOR_FRICTION 6u
#define ROBOT_DEVICE_CONFIG_REF_MOTOR_ARM 7u

#define ROBOT_DEVICE_SOURCE_NONE 0xFFFFu

typedef struct
{
    const char *name;
    uint16_t source_id;
    uint8_t kind;
    uint8_t config_ref;
    uint8_t config_index;
    uint8_t fallback_bus;
} robot_device_config_entry_t;

typedef struct
{
    uint8_t count;
    robot_device_config_entry_t entry[ROBOT_DEVICE_CONFIG_MAX];
} robot_device_config_table_t;

#define ROBOT_DEVICE_ENTRY_MOTOR(name_, config_ref_, index_, fallback_bus_, source_id_) \
    {(name_), (uint16_t)(source_id_), ROBOT_DEVICE_TABLE_KIND_MOTOR, (config_ref_), (index_), (fallback_bus_)}

#define ROBOT_DEFAULT_DEVICE_TABLE \
    { \
        .count = (uint8_t)ROBOT_DEVICE_CONFIG_MAX, \
        .entry = { \
            ROBOT_DEVICE_ENTRY_MOTOR("motor.chassis0", ROBOT_DEVICE_CONFIG_REF_MOTOR_CHASSIS, 0u, 1u, ACTUATOR_ID_CHASSIS0), \
            ROBOT_DEVICE_ENTRY_MOTOR("motor.chassis1", ROBOT_DEVICE_CONFIG_REF_MOTOR_CHASSIS, 1u, 1u, ACTUATOR_ID_CHASSIS1), \
            ROBOT_DEVICE_ENTRY_MOTOR("motor.chassis2", ROBOT_DEVICE_CONFIG_REF_MOTOR_CHASSIS, 2u, 1u, ACTUATOR_ID_CHASSIS2), \
            ROBOT_DEVICE_ENTRY_MOTOR("motor.chassis3", ROBOT_DEVICE_CONFIG_REF_MOTOR_CHASSIS, 3u, 1u, ACTUATOR_ID_CHASSIS3), \
            ROBOT_DEVICE_ENTRY_MOTOR("motor.yaw", ROBOT_DEVICE_CONFIG_REF_MOTOR_YAW, 0u, 1u, ACTUATOR_ID_YAW), \
            ROBOT_DEVICE_ENTRY_MOTOR("motor.yaw_upper", ROBOT_DEVICE_CONFIG_REF_MOTOR_YAW_UPPER, 0u, 1u, ACTUATOR_ID_YAW_UPPER), \
            ROBOT_DEVICE_ENTRY_MOTOR("motor.pitch", ROBOT_DEVICE_CONFIG_REF_MOTOR_PITCH, 0u, 1u, ACTUATOR_ID_PITCH), \
            ROBOT_DEVICE_ENTRY_MOTOR("motor.trigger", ROBOT_DEVICE_CONFIG_REF_MOTOR_TRIGGER, 0u, 1u, ACTUATOR_ID_TRIGGER), \
            ROBOT_DEVICE_ENTRY_MOTOR("motor.friction0", ROBOT_DEVICE_CONFIG_REF_MOTOR_FRICTION, 0u, 2u, ACTUATOR_ID_FRICTION0), \
            ROBOT_DEVICE_ENTRY_MOTOR("motor.friction1", ROBOT_DEVICE_CONFIG_REF_MOTOR_FRICTION, 1u, 2u, ACTUATOR_ID_FRICTION1), \
            ROBOT_DEVICE_ENTRY_MOTOR("motor.friction2", ROBOT_DEVICE_CONFIG_REF_MOTOR_FRICTION, 2u, 2u, ACTUATOR_ID_FRICTION2), \
            ROBOT_DEVICE_ENTRY_MOTOR("motor.friction3", ROBOT_DEVICE_CONFIG_REF_MOTOR_FRICTION, 3u, 2u, ACTUATOR_ID_FRICTION3), \
            ROBOT_DEVICE_ENTRY_MOTOR("motor.arm0", ROBOT_DEVICE_CONFIG_REF_MOTOR_ARM, 0u, 1u, ACTUATOR_ID_ARM_J0), \
            ROBOT_DEVICE_ENTRY_MOTOR("motor.arm1", ROBOT_DEVICE_CONFIG_REF_MOTOR_ARM, 1u, 2u, ACTUATOR_ID_ARM_J1), \
            ROBOT_DEVICE_ENTRY_MOTOR("motor.arm2", ROBOT_DEVICE_CONFIG_REF_MOTOR_ARM, 2u, 2u, ACTUATOR_ID_ARM_J2), \
            ROBOT_DEVICE_ENTRY_MOTOR("motor.arm3", ROBOT_DEVICE_CONFIG_REF_MOTOR_ARM, 3u, 2u, ACTUATOR_ID_ARM_J3), \
            ROBOT_DEVICE_ENTRY_MOTOR("motor.arm4", ROBOT_DEVICE_CONFIG_REF_MOTOR_ARM, 4u, 2u, ACTUATOR_ID_ARM_J4), \
            ROBOT_DEVICE_ENTRY_MOTOR("motor.arm5", ROBOT_DEVICE_CONFIG_REF_MOTOR_ARM, 5u, 2u, ACTUATOR_ID_ARM_J5), \
        }, \
    }

#endif
