/*
 * SPDX-FileCopyrightText: 2026 Xie Yuhan <2811158416@qq.com>
 * SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
 */

#ifndef ROBOT_CONFIG_SCHEMA_H
#define ROBOT_CONFIG_SCHEMA_H

#include <stdint.h>

#ifndef MOTOR_ARM_JOINT_COUNT
#define MOTOR_ARM_JOINT_COUNT 0u
#endif

#ifndef ROBOT_DEVICE_CONFIG_MAX
#define ROBOT_DEVICE_CONFIG_MAX (12u + MOTOR_ARM_JOINT_COUNT)
#endif

#define ROBOT_DEVICE_TABLE_KIND_MOTOR 1u

#define ROBOT_DEVICE_TABLE_MOTOR_GROUP_CHASSIS 0u
#define ROBOT_DEVICE_TABLE_MOTOR_GROUP_YAW 1u
#define ROBOT_DEVICE_TABLE_MOTOR_GROUP_YAW_UPPER 2u
#define ROBOT_DEVICE_TABLE_MOTOR_GROUP_PITCH 3u
#define ROBOT_DEVICE_TABLE_MOTOR_GROUP_TRIGGER 4u
#define ROBOT_DEVICE_TABLE_MOTOR_GROUP_FRICTION 5u
#define ROBOT_DEVICE_TABLE_MOTOR_GROUP_ARM 6u

typedef struct
{
    uint8_t kind;
    uint8_t group;
    uint8_t group_index;
    uint8_t reserved0;
} robot_device_config_entry_t;

typedef struct
{
    uint8_t count;
    robot_device_config_entry_t entry[ROBOT_DEVICE_CONFIG_MAX];
} robot_device_config_table_t;

#define ROBOT_DEVICE_ENTRY_MOTOR(group_, index_) \
    {ROBOT_DEVICE_TABLE_KIND_MOTOR, (group_), (index_), 0u}

#define ROBOT_DEFAULT_DEVICE_TABLE \
    { \
        .count = (uint8_t)ROBOT_DEVICE_CONFIG_MAX, \
        .entry = { \
            ROBOT_DEVICE_ENTRY_MOTOR(ROBOT_DEVICE_TABLE_MOTOR_GROUP_CHASSIS, 0u), \
            ROBOT_DEVICE_ENTRY_MOTOR(ROBOT_DEVICE_TABLE_MOTOR_GROUP_CHASSIS, 1u), \
            ROBOT_DEVICE_ENTRY_MOTOR(ROBOT_DEVICE_TABLE_MOTOR_GROUP_CHASSIS, 2u), \
            ROBOT_DEVICE_ENTRY_MOTOR(ROBOT_DEVICE_TABLE_MOTOR_GROUP_CHASSIS, 3u), \
            ROBOT_DEVICE_ENTRY_MOTOR(ROBOT_DEVICE_TABLE_MOTOR_GROUP_YAW, 0u), \
            ROBOT_DEVICE_ENTRY_MOTOR(ROBOT_DEVICE_TABLE_MOTOR_GROUP_YAW_UPPER, 0u), \
            ROBOT_DEVICE_ENTRY_MOTOR(ROBOT_DEVICE_TABLE_MOTOR_GROUP_PITCH, 0u), \
            ROBOT_DEVICE_ENTRY_MOTOR(ROBOT_DEVICE_TABLE_MOTOR_GROUP_TRIGGER, 0u), \
            ROBOT_DEVICE_ENTRY_MOTOR(ROBOT_DEVICE_TABLE_MOTOR_GROUP_FRICTION, 0u), \
            ROBOT_DEVICE_ENTRY_MOTOR(ROBOT_DEVICE_TABLE_MOTOR_GROUP_FRICTION, 1u), \
            ROBOT_DEVICE_ENTRY_MOTOR(ROBOT_DEVICE_TABLE_MOTOR_GROUP_FRICTION, 2u), \
            ROBOT_DEVICE_ENTRY_MOTOR(ROBOT_DEVICE_TABLE_MOTOR_GROUP_FRICTION, 3u), \
            ROBOT_DEVICE_ENTRY_MOTOR(ROBOT_DEVICE_TABLE_MOTOR_GROUP_ARM, 0u), \
            ROBOT_DEVICE_ENTRY_MOTOR(ROBOT_DEVICE_TABLE_MOTOR_GROUP_ARM, 1u), \
            ROBOT_DEVICE_ENTRY_MOTOR(ROBOT_DEVICE_TABLE_MOTOR_GROUP_ARM, 2u), \
            ROBOT_DEVICE_ENTRY_MOTOR(ROBOT_DEVICE_TABLE_MOTOR_GROUP_ARM, 3u), \
            ROBOT_DEVICE_ENTRY_MOTOR(ROBOT_DEVICE_TABLE_MOTOR_GROUP_ARM, 4u), \
            ROBOT_DEVICE_ENTRY_MOTOR(ROBOT_DEVICE_TABLE_MOTOR_GROUP_ARM, 5u), \
        }, \
    }

#endif
