/*
 * SPDX-FileCopyrightText: 2026 Xie Yuhan <2811158416@qq.com>
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ROBOT_TASK_BUILD_CONFIG_H
#define ROBOT_TASK_BUILD_CONFIG_H

#ifndef ROBOT_TASK_BUILD_STARTUP_SERVICE
#define ROBOT_TASK_BUILD_STARTUP_SERVICE 1
#endif

#ifndef ROBOT_TASK_BUILD_CALIBRATION
#define ROBOT_TASK_BUILD_CALIBRATION 1
#endif

#ifndef ROBOT_TASK_BUILD_RC_SBUS
#define ROBOT_TASK_BUILD_RC_SBUS 1
#endif

#ifndef ROBOT_TASK_BUILD_HEALTH_MONITOR
#define ROBOT_TASK_BUILD_HEALTH_MONITOR 1
#endif

#ifndef ROBOT_TASK_BUILD_SDLOG
#define ROBOT_TASK_BUILD_SDLOG 1
#endif

#ifndef ROBOT_TASK_BUILD_CAN_COMMAND_TX
#define ROBOT_TASK_BUILD_CAN_COMMAND_TX 1
#endif

#ifndef ROBOT_TASK_BUILD_CAN_FEEDBACK_RX
#define ROBOT_TASK_BUILD_CAN_FEEDBACK_RX 1
#endif

#ifndef ROBOT_TASK_BUILD_CLASSIC_CHASSIS
#define ROBOT_TASK_BUILD_CLASSIC_CHASSIS 1
#endif

#ifndef ROBOT_TASK_BUILD_WHEELLEG_SERVO
#define ROBOT_TASK_BUILD_WHEELLEG_SERVO 1
#endif

#ifndef ROBOT_TASK_BUILD_WHEELLEG_MIT
#define ROBOT_TASK_BUILD_WHEELLEG_MIT 1
#endif

#ifndef ROBOT_TASK_BUILD_SINGLE_GIMBAL
#define ROBOT_TASK_BUILD_SINGLE_GIMBAL 1
#endif

#ifndef ROBOT_TASK_BUILD_DUAL_YAW_GIMBAL
#define ROBOT_TASK_BUILD_DUAL_YAW_GIMBAL 1
#endif

#ifndef ROBOT_TASK_BUILD_ARM
#define ROBOT_TASK_BUILD_ARM 1
#endif

#ifndef ROBOT_TASK_BUILD_IMU
#define ROBOT_TASK_BUILD_IMU 1
#endif

#ifndef ROBOT_TASK_BUILD_HOST_LINK
#define ROBOT_TASK_BUILD_HOST_LINK 1
#endif

#ifndef ROBOT_TASK_BUILD_ELRS_LINK
#define ROBOT_TASK_BUILD_ELRS_LINK 1
#endif

#ifndef ROBOT_TASK_BUILD_REFEREE_RX
#define ROBOT_TASK_BUILD_REFEREE_RX 1
#endif

#ifndef ROBOT_TASK_BUILD_BATTERY_MONITOR
#define ROBOT_TASK_BUILD_BATTERY_MONITOR 1
#endif

#ifndef ROBOT_TASK_BUILD_SERVO
#define ROBOT_TASK_BUILD_SERVO 1
#endif

#ifndef ROBOT_TASK_BUILD_STATUS_LED
#define ROBOT_TASK_BUILD_STATUS_LED 1
#endif

#ifndef ROBOT_TASK_BUILD_SHOOT_RM
#define ROBOT_TASK_BUILD_SHOOT_RM 1
#endif

#define ROBOT_TASK_BUILD_ANY_GIMBAL \
    (ROBOT_TASK_BUILD_SINGLE_GIMBAL || ROBOT_TASK_BUILD_DUAL_YAW_GIMBAL)

#endif
