#ifndef TEST_ROBOT_FAULT_TYPES_H
#define TEST_ROBOT_FAULT_TYPES_H
enum { ROBOT_FAULT_REASON_ERROR_HANDLER = 3u, ROBOT_FAULT_REASON_HARDFAULT = 4u,
       ROBOT_FAULT_REASON_STACK_OVERFLOW = 1u, ROBOT_FAULT_REASON_NMI = 8u,
       ROBOT_FAULT_REASON_ASSERT = 9u, ROBOT_FAULT_REASON_DEFAULT_INTERRUPT = 11u };
#endif
