#ifndef HOST_TEST_ROBOT_CONFIG_H
#define HOST_TEST_ROBOT_CONFIG_H

#define ROBOT_TASK_BUILD_CLASSIC_CHASSIS 1
#define ROBOT_TASK_BUILD_SINGLE_GIMBAL 1
#define ROBOT_TASK_BUILD_DUAL_YAW_GIMBAL 0
#define ROBOT_TASK_BUILD_SHOOT_RM 1
#define ROBOT_TASK_BUILD_WHEELLEG_MIT 1
#define ROBOT_TASK_BUILD_ARM 1
#define ROBOT_TASK_BUILD_IMU 1

#endif
